version: "3.2"
services:
  db:
    image: mongo
    networks:
      - consignment
    deploy:
      restart_policy:
        condition: on-failure
  vessel-service:
    image: vessel-service
    networks:
      - consignment
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  consignment-service:
    image: consignment-service
    networks:
      - consignment
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  consignment:
    external: true
